/* (T3) bd0103_commenting_et.baf
after Skie woke the PC up on the day of departure */
IF
	Global("bd_plot","global",55)
	Global("xxBiff_BD_PLAY_ONCE","BD0103",0)
	Global("BD_OT_DELAY","BD0103",0)
	IsValidForPartyDialog("xxBiff")  
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("BD_OT_DELAY","BD0103",1)
		SetGlobal("xxBiff_BD_PLAY_ONCE","BD0103",1)
		Wait(1)
		DisplayStringWait("xxBiff",~This is the big day!~)
		SetGlobal("BD_OT_DELAY","BD0103",0)
		SetInterrupt(TRUE)
		Continue()
END	