/* (T3) bd0114_commenting.baf */
IF
	Global("BD_POINT6","BD0114",4)  // Spider Cave: Rhinoceros Beetle appeared
	StateCheck("BDBEETRH",STATE_REALLY_DEAD)  // Rhinoceros Beetle
	Global("xxBiff_BD_BEETLE","BD0114",0)  
	!GlobalTimerNotExpired("BD_TIMER_RHINOTALK","BD0114")  
	IfValidForPartyDialog("xxBiff")  
THEN
	RESPONSE #100
		DisplayStringHead("xxBiff",~Wow. This thing always makes me a bit nervous.~)
		SetGlobal("xxBiff_BD_BEETLE","BD0114",1)  
END