/* xxbdcut64x.baf
Biff will not join after PC escaped from prison (simplifies scripting) */
IF
	Global("xxBiff_SoDEndMove","bd6200",1) //same as in xxbd6200.bcs 
	InMyArea("xxBiff")
	!Dead("xxBiff")  
	!InParty("xxBiff")  
THEN
	RESPONSE #100
		CutSceneId(Player1)
		SetGlobal("xxBiff_SoDEndMove","bd6200",2)
		ActionOverride("xxBiff",LeaveAreaLUA("bd6100","",[xxx.yyy],SE)) //chose some coordinates beneath the trees northseast of the clearing 
		SmallWait(10)
		Continue()
END




