/* bd4601_commenting_et.baf */
/* (T3) Comment in the Avernus Elevator */
IF
	Global("xxBiff_bd_hellevator_ot","bd4601",0)  
	IfValidForPartyDialog("xxBiff")  
	!GlobalTimerNotExpired("bd_hellevator_timer","bd4601")  
	!ActuallyInCombat()
THEN
	RESPONSE #100
		SetGlobal("xxBiff_bd_hellevator_ot","bd4601",1)  // Avernus Elevator
		SetGlobalTimer("bd_hellevator_timer","bd4601",7)  
		DisplayStringHead("xxBiff",~Better not be afraid of heights! ... And demons.~)
 		Continue()
END